name: Simple Local
on: push
jobs:
   build-node:
       runs-on: ubuntu-latest
       container: node:18
       steps:
           - uses: actions/checkout@v3
           - run: node --version
           - run: npm --version
           - run: npm install --save moment
           - run: node app.js
